### ISSUE TITLE
Resdesign Consultation page

### ISSUE THREAD

**Issue by joelsajichacko** [coronasafe/citizen#24]
![ayushman 1](https://user-images.githubusercontent.com/45791338/124293633-7aed6680-db74-11eb-8ce5-0561a235ce46.png)
![ayushman 2](https://user-images.githubusercontent.com/45791338/124295140-1f23dd00-db76-11eb-9674-c49a30dbc4e5.png)

**Comment by peeyush14goyal** [comment]
@vigneshhari All fields are not available in API ? Can you please check?
